name: build spring boot application
on: push

jobs:
  build:
    name: build spring
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: 02/demo
        push: true
        tags: pepsicolav13/spring-boot
        platforms: |
          linux/arm64
